// Note: all units in lbs CO2

const FLIGHT_EMISSIONS_PER_MILE = .32;
const AUTO_EMISSIONS_PER_GALLON = 20;

const NATURAL_GAS_EMISSIONS_PER_THOUSAND_CUBIC_FOOT = 121;
const ELECTRIC_EMISSIONS_PER_KWH = .954;

module.exports = {
    FLIGHT_EMISSIONS_PER_MILE,
    AUTO_EMISSIONS_PER_GALLON,
    NATURAL_GAS_EMISSIONS_PER_THOUSAND_CUBIC_FOOT,
    ELECTRIC_EMISSIONS_PER_KWH,
}
